import { BlogPost, MeetupEvent } from './content.models';

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'agentic-apps-2026',
    slug: 'agentic-apps-2026',
    title: 'Agentic apps in 2026: from chatbot to product workflow',
    excerpt: 'AI agents are moving from chat windows into real workflows: planning, tool use, memory, approvals and product telemetry.',
    category: 'AI Agents',
    tags: ['AI agents', 'product design', 'automation'],
    author: 'Webaby Labs',
    publishedAt: '2026-06-02',
    readingMinutes: 5,
    featured: true,
    body: [
      'The most useful AI products are no longer just chat interfaces. They are workflow systems where a model can decide what context it needs, call a tool, ask for approval, and hand work to another specialised agent.',
      'For mobile and web apps this changes product design. The best user experience is not an oversized text box. It is a small set of high-confidence actions: draft a document, compare options, prepare a support reply, create a learning plan, or run a safe business task.',
      'Teams should start with narrow agents that have clear permissions, observable traces and human checkpoints. The value is not magic autonomy. The value is removing repeated coordination work while keeping the user in control.',
    ],
  },
  {
    id: 'mcp-servers-product-architecture',
    slug: 'mcp-servers-product-architecture',
    title: 'MCP servers: the new integration layer for AI tools',
    excerpt: 'Model Context Protocol gives AI systems a standard way to work with tools, resources and prompts across products.',
    category: 'MCP',
    tags: ['MCP', 'integration', 'tooling'],
    author: 'Webaby Labs',
    publishedAt: '2026-06-02',
    readingMinutes: 6,
    featured: true,
    body: [
      'Model Context Protocol is becoming a practical bridge between language models and external systems. Instead of writing one-off integrations for every assistant, teams can expose resources, prompts and tools through an MCP server.',
      'This matters for product teams because it separates the AI interface from business systems. A CRM, document archive, analytics dashboard or internal workflow can expose stable capabilities while different agents consume them.',
      'The architectural lesson is simple: treat MCP servers like production APIs. Add authentication, rate limits, audit logs, tool descriptions that are hard to misuse, and clear boundaries around sensitive operations.',
    ],
  },
  {
    id: 'mobile-ai-on-device-vs-cloud',
    slug: 'mobile-ai-on-device-vs-cloud',
    title: 'Mobile AI: when to run models on-device and when to use cloud',
    excerpt: 'Modern mobile apps can mix on-device intelligence with cloud models for privacy, latency and richer reasoning.',
    category: 'Mobile AI',
    tags: ['mobile apps', 'on-device AI', 'privacy'],
    author: 'Webaby Labs',
    publishedAt: '2026-06-02',
    readingMinutes: 5,
    body: [
      'On-device AI is ideal for private, low-latency tasks: summarising local content, ranking suggestions, personalising lessons, detecting intent or helping the user without sending every interaction to a server.',
      'Cloud models still win when the task needs broad reasoning, large context windows, fresh external data or expensive multimodal processing. The best apps often combine both: local first, cloud when needed.',
      'A good mobile AI architecture makes this choice explicit. Define what data may leave the device, what is cached locally, and how the app behaves when connectivity or quota is limited.',
    ],
  },
  {
    id: 'web-apps-with-ai-copilots',
    slug: 'web-apps-with-ai-copilots',
    title: 'Designing AI copilots for web applications',
    excerpt: 'A useful copilot is contextual, explainable and close to the user’s current task rather than a disconnected chat widget.',
    category: 'Web Apps',
    tags: ['web apps', 'copilots', 'UX'],
    author: 'Webaby Labs',
    publishedAt: '2026-06-02',
    readingMinutes: 4,
    body: [
      'The strongest AI copilots live inside the workflow. They know the current screen, selected item, permissions, recent changes and the next likely action.',
      'For SaaS products, a copilot should not replace the interface. It should accelerate the interface: create filters, explain a chart, draft a message, suggest an automation or summarise account history.',
      'The key UX pattern is reversible action. Let the copilot prepare work, show what will change, and ask the user to confirm. Trust grows when the system is transparent.',
    ],
  },
  {
    id: 'ai-for-educational-games',
    slug: 'ai-for-educational-games',
    title: 'AI in educational games: personalisation without losing play',
    excerpt: 'AI can adapt learning paths, hints and feedback while preserving the joy of discovery.',
    category: 'EdTech',
    tags: ['edtech', 'games', 'personalisation'],
    author: 'Webaby Labs',
    publishedAt: '2026-06-02',
    readingMinutes: 4,
    body: [
      'Educational games work best when learning is embedded into play. AI can help by adjusting difficulty, generating hints, detecting frustration and creating practice tasks that fit the learner.',
      'The risk is turning a game into a worksheet. AI should support agency, not remove it. Let players explore, fail safely and receive feedback that feels like part of the world.',
      'For children and families, privacy and moderation matter as much as intelligence. Keep data minimal, avoid unnecessary profiling and make parent-facing controls clear.',
    ],
  },
  {
    id: 'secure-ai-tool-use',
    slug: 'secure-ai-tool-use',
    title: 'Secure AI tool use: permissions, audit logs and human approval',
    excerpt: 'Agentic systems become safer when every tool call is permissioned, observable and reversible where possible.',
    category: 'Security',
    tags: ['AI security', 'agents', 'governance'],
    author: 'Webaby Labs',
    publishedAt: '2026-06-02',
    readingMinutes: 5,
    body: [
      'AI agents become powerful when they use tools. They also become risky. A model that can read files, send emails, update records or deploy code needs strict boundaries.',
      'Start by classifying tools: read-only, draft-only, reversible write, irreversible write and external communication. Each class needs a different approval model.',
      'Audit logs are not optional. Teams need to know what the agent saw, what it decided, what it called and what changed. Without traceability, debugging and compliance become guesswork.',
    ],
  },
  {
    id: 'ai-native-backends',
    slug: 'ai-native-backends',
    title: 'AI-native backends: queues, traces and model-aware APIs',
    excerpt: 'Backend systems for AI features need streaming, retries, observability and context management from day one.',
    category: 'Backend',
    tags: ['backend', 'observability', 'AI infrastructure'],
    author: 'Webaby Labs',
    publishedAt: '2026-06-02',
    readingMinutes: 5,
    body: [
      'AI features stress a backend differently than classic CRUD. Requests may stream, fan out to tools, wait for model responses, retry after failures or produce partial results.',
      'A robust AI backend has queues for long tasks, idempotency keys for tool calls, structured traces for every run and clear storage rules for prompts, outputs and user data.',
      'The product team should also track quality metrics: acceptance rate, edit distance, tool failure rate, escalation rate and time saved. Latency alone does not tell the story.',
    ],
  },
  {
    id: 'multimodal-interfaces',
    slug: 'multimodal-interfaces',
    title: 'Multimodal interfaces: text, voice, images and app context',
    excerpt: 'Users increasingly expect apps to understand screenshots, voice, documents and structured app state.',
    category: 'UX',
    tags: ['multimodal AI', 'UX', 'voice'],
    author: 'Webaby Labs',
    publishedAt: '2026-06-02',
    readingMinutes: 4,
    body: [
      'Multimodal AI is changing how people ask for help. A user may point at a screenshot, speak a request, upload a document or ask the app to explain a chart.',
      'The best interface combines modes without forcing them. Voice is great for intent, images are great for reference, text is great for precision, and structured app context keeps the answer grounded.',
      'Designers should think in handoffs: voice to action draft, screenshot to diagnosis, document to summary, summary to workflow. The interaction should end with something useful happening.',
    ],
  },
  {
    id: 'seo-for-ssr-angular-apps',
    slug: 'seo-for-ssr-angular-apps',
    title: 'SEO for Angular SSR apps: what actually matters',
    excerpt: 'SSR gives crawlers HTML, but rankings still depend on content quality, metadata, internal links and performance.',
    category: 'SEO',
    tags: ['Angular', 'SSR', 'SEO'],
    author: 'Webaby Labs',
    publishedAt: '2026-06-02',
    readingMinutes: 5,
    body: [
      'Server-side rendering solves one important problem: crawlers and social previews can see real HTML. But SSR alone is not a ranking strategy.',
      'A strong Angular SEO setup includes unique titles and descriptions, canonical links, structured data, a sitemap, accessible headings, descriptive internal links and pages that load quickly.',
      'Content architecture matters too. A blog, product tutorials, event pages and topic hubs create a web of meaningful links that helps search engines understand what the site is about.',
    ],
  },
  {
    id: 'future-of-it-development',
    slug: 'future-of-it-development',
    title: 'The future of IT development: smaller teams, stronger tools',
    excerpt: 'AI-assisted development is shifting teams toward faster prototypes, better tests and more product thinking.',
    category: 'Development',
    tags: ['software development', 'AI coding', 'product teams'],
    author: 'Webaby Labs',
    publishedAt: '2026-06-02',
    readingMinutes: 4,
    body: [
      'AI coding tools are changing the rhythm of development. They help teams explore implementations, write tests, inspect logs and turn rough ideas into working prototypes faster.',
      'The bottleneck moves from typing code to making good decisions. Teams still need architecture, security, product taste, testing discipline and clear ownership.',
      'The winners will be teams that use AI to increase iteration quality, not just output volume. Faster shipping only helps when the product gets clearer with every release.',
    ],
  },
];

export const MEETUP_EVENTS: MeetupEvent[] = [
  {
    id: 'ai-agents-for-products',
    slug: 'ai-agents-for-products',
    title: 'AI Agents for Real Products',
    summary: 'A practical meetup about designing agentic features for mobile and web apps.',
    description: [
      'We will look at agent workflows, tool permissions, MCP servers and human-in-the-loop approvals.',
      'The session is aimed at founders, developers and product builders who want to add AI features without turning the app into a vague chatbot.',
    ],
    startsAt: '2026-07-10T18:00:00+02:00',
    location: 'Online',
    capacity: 60,
    tags: ['AI agents', 'MCP', 'product'],
  },
  {
    id: 'angular-ssr-seo-workshop',
    slug: 'angular-ssr-seo-workshop',
    title: 'Angular SSR and SEO Workshop',
    summary: 'A focused event on metadata, structured data, performance and searchable Angular routes.',
    description: [
      'We will walk through an Angular SSR SEO checklist and discuss real-world indexing problems.',
      'Topics include sitemap design, canonical URLs, Open Graph, JSON-LD and content architecture.',
    ],
    startsAt: '2026-08-21T17:30:00+02:00',
    location: 'Warsaw / Online hybrid',
    capacity: 40,
    tags: ['Angular', 'SSR', 'SEO'],
  },
  {
    id: 'mobile-ai-patterns',
    slug: 'mobile-ai-patterns',
    title: 'Mobile AI Patterns for 2026',
    summary: 'On-device AI, cloud reasoning and privacy-first mobile product patterns.',
    description: [
      'This meetup explores when AI should run locally, when it should call the cloud and how to keep the user experience simple.',
      'We will discuss educational apps, personal assistants, offline-first UX and data minimisation.',
    ],
    startsAt: '2026-09-18T18:00:00+02:00',
    location: 'Online',
    capacity: 80,
    tags: ['mobile AI', 'privacy', 'apps'],
  },
];
