name: webaby-page runner (NEW on domain)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

concurrency:
  group: webaby-page-prod
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: self-hosted
    timeout-minutes: 60

    env:
      # >>> ZMIANA: docelowy docroot POZA _work
      DEST_DIR: /var/www/webaby-page/current

    steps:
      - uses: actions/checkout@v4
        # (opcjonalnie – jeśli kiedyś zostałbyś przy _work, można dodać clean:false)
        # with:
        #   clean: false

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Angular (production)
        run: npm run build

      - name: Detect build output dir
        id: outdir
        shell: bash
        run: |
          set -e
          OUT=$(ls -d dist/*/browser 2>/dev/null || ls -d dist/*)
          echo "BUILD_OUT=$OUT" >> $GITHUB_ENV
          echo "Build output: $OUT"

      # --- PWA (opcjonalnie) – ZOSTAWIAM dokładnie jak u Ciebie, tylko działa z nowym BUILD_OUT ---
      # - uses: actions/checkout@v4
      #   with:
      #     repository: maciejmar/basketball-game
      #     path: basketball-pwa
      #     # jeśli prywatne: token: ${{ secrets.GH_PAT }}
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: 'npm'
      #     cache-dependency-path: basketball-pwa/package-lock.json
      # - name: Build PWA (/basketball-pwa)
      #   working-directory: basketball-pwa
      #   run: npx ng build --configuration production --base-href /basketball-pwa/ --deploy-url /basketball-pwa/
      # - name: Copy PWA into site's build
      #   shell: bash
      #   run: |
      #     PWA_DIR=$(ls -d basketball-pwa/dist/*/browser 2>/dev/null || ls -d basketball-pwa/dist/*)
      #     mkdir -p "$BUILD_OUT/basketball-pwa"
      #     rsync -a --delete "$PWA_DIR/" "$BUILD_OUT/basketball-pwa/"

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust server host key
        run: ssh-keyscan -Hv ${{ secrets.OVH_VPS_IP }} >> ~/.ssh/known_hosts

      - name: SSH smoke test
        run: ssh -o BatchMode=yes ubuntu@${{ secrets.OVH_VPS_IP }} "echo CONNECTED && hostname"

      - name: Create dest dir (sudo)
        run: ssh ubuntu@${{ secrets.OVH_VPS_IP }} "sudo mkdir -p '${{ env.DEST_DIR }}'"

      - name: Rsync build → /var/www/webaby-page/current (sudo)
        run: |
          rsync -az --delete \
            --rsync-path="sudo rsync" \
            "${BUILD_OUT}/" \
            ubuntu@${{ secrets.OVH_VPS_IP }}:"${{ env.DEST_DIR }}/"

      - name: Fix perms (opcjonalnie, ale polecane)
        run: |
          ssh ubuntu@${{ secrets.OVH_VPS_IP }} "\
            sudo find '${{ env.DEST_DIR }}' -type d -exec chmod 755 {} \; && \
            sudo find '${{ env.DEST_DIR }}' -type f -exec chmod 644 {} \; && \
            sudo chown -R root:root '${{ env.DEST_DIR }}'"

      - name: Reload Nginx
        run: ssh ubuntu@${{ secrets.OVH_VPS_IP }} "sudo nginx -t && sudo systemctl reload nginx"
